{% set name = "RanForCorine" %}
{% set version = "0.4.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/AntjeUhde/RanForCorine.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - RanForCorine

about:
  home: https://github.com/AntjeUhde/RanForCorine
  license: MIT
